### ISSUE TITLE
Error 403/forbidden on trying to connect from remote

### ISSUE THREAD

**Issue by Roman-jj** [lgsvl/PythonAPI#8]
Hi, when trying to connect to the simulator using the python API, I'm getting an error that I guess could have to do with system proxies again.

On one machine I have the simulator running fine in Unity, WebUI ist working correctly on port 8080, and I can connect to my rosbridge on a remote machine.
Now I installed the python API on the remote machine and tried to connect to the simulator running an API only simulation, but I only get error 403.

For debugging I tried to open a websocket through a python shell and I get the following output:
`>>> soc=lgsvl.remote.Remote('53.63.112.62',8081)
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/lhome/joerger/GIT/PythonAPI/lgsvl/remote.py", line 28, in run
    self.loop.run_until_complete(self.process())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/lhome/joerger/GIT/PythonAPI/lgsvl/remote.py", line 36, in process
    self.websocket = await websockets.connect(self.endpoint, compression=None)
  File "/lhome/joerger/.local/lib/python3.6/site-packages/websockets/py35/client.py", line 20, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "/lhome/joerger/.local/lib/python3.6/site-packages/websockets/client.py", line 286, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 403`
and then after interrupt
`^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lhome/joerger/GIT/PythonAPI/lgsvl/remote.py", line 23, in __init__
    self.sem.acquire()
  File "/usr/lib/python3.6/threading.py", line 426, in acquire
    self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt`

Currently I can't try this on the local machine since python3 is not installed, but when I try to open localhost:8081 in a browser I get 403 forbidden as well.

Could there be any other issue than the proxy settings?

Thanks in advance

**Comment by Roman-jj** [comment]
Sorry, realized it's port 8181 and not 8081.

I think the problem is a combination of proxy and firewall issues, as I can't even ping the machine running the simulation...
Will leave this open until I've fixed it though

**Comment by Roman-jj** [comment]
Tried to run a few more tests and it seems it's another proxy problem with python/websockets/...

Connecting locally (localhost) works without problems.
When trying to connect from a remote machine I get the following error:
`>>> sim=lgsvl.Simulator('53.58.82.31',8181)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/lhome/joerger/GIT/PythonAPI/lgsvl/remote.py", line 28, in run
    self.loop.run_until_complete(self.process())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/lhome/joerger/GIT/PythonAPI/lgsvl/remote.py", line 36, in process
    self.websocket = await websockets.connect(self.endpoint, compression=None)
  File "/lhome/joerger/.local/lib/python3.6/site-packages/websockets/client.py", line 537, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('53.58.82.31', 8181)

^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lhome/joerger/GIT/PythonAPI/lgsvl/utils.py", line 21, in new_f
    return f(*args, **kwargs)
  File "/lhome/joerger/GIT/PythonAPI/lgsvl/simulator.py", line 26, in __init__
    self.remote = Remote(address, port)
  File "/lhome/joerger/GIT/PythonAPI/lgsvl/remote.py", line 23, in __init__
    self.sem.acquire()
  File "/usr/lib/python3.6/threading.py", line 426, in acquire
    self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt`

I then tried to connect using the python websocket-client package and got this error:
`>>> ws=websocket.create_connection('ws://53.58.82.31:8181')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lhome/joerger/.local/lib/python3.6/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/lhome/joerger/.local/lib/python3.6/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/lhome/joerger/.local/lib/python3.6/site-packages/websocket/_http.py", line 122, in connect
    sock = _tunnel(sock, hostname, port, auth)
  File "/lhome/joerger/.local/lib/python3.6/site-packages/websocket/_http.py", line 293, in _tunnel
    "failed CONNECT via proxy status: %r" % status)
websocket._exceptions.WebSocketProxyException: failed CONNECT via proxy status: 504`
Same error when giving proxy server as parameter (`ws=websocket.create_connection('ws://53.58.82.31:8181', http_proxy_host="localhost", http_proxy_port=3128)`)

On the machine with the simulator, I had `sudo tcpdump -v -nS dst port 8181` running and got the following output:
`tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
10:35:09.589369 IP (tos 0x0, ttl 63, id 64789, offset 0, flags [DF], proto TCP (6), length 60)
    53.58.83.77.53108 > 53.58.82.31.8181: Flags [S], cksum 0xba4f (correct), seq 4242272123, win 29200, options [mss 1460,sackOK,TS val 2884862986 ecr 0,nop,wscale 7], length 0
10:47:05.349041 IP (tos 0x0, ttl 63, id 25541, offset 0, flags [DF], proto TCP (6), length 60)
    53.58.83.77.53270 > 53.58.82.31.8181: Flags [S], cksum 0x37e2 (correct), seq 3548229295, win 29200, options [mss 1460,sackOK,TS val 2885578741 ecr 0,nop,wscale 7], length 0
10:47:05.349447 IP (tos 0x0, ttl 63, id 48477, offset 0, flags [DF], proto TCP (6), length 60)
    53.58.83.77.53272 > 53.58.82.31.8181: Flags [S], cksum 0x7196 (correct), seq 3627970615, win 29200, options [mss 1460,sackOK,TS val 2885578742 ecr 0,nop,wscale 7], length 0
11:05:09.198766 IP (tos 0x0, ttl 58, id 15032, offset 0, flags [DF], proto TCP (6), length 60)
    53.55.11.194.25480 > 53.58.82.31.8181: Flags [S], cksum 0xb3f3 (correct), seq 1748941974, win 12288, options [mss 1460,nop,wscale 6,sackOK,TS val 2478071732 ecr 0], length 0
11:10:52.745063 IP (tos 0x0, ttl 58, id 22891, offset 0, flags [DF], proto TCP (6), length 60)
    53.55.11.194.35648 > 53.58.82.31.8181: Flags [S], cksum 0xffa9 (correct), seq 4074602639, win 12288, options [mss 1460,nop,wscale 6,sackOK,TS val 2478415272 ecr 0], length 0
11:12:56.912545 IP (tos 0x0, ttl 58, id 57516, offset 0, flags [DF], proto TCP (6), length 60)
    53.55.11.194.39411 > 53.58.82.31.8181: Flags [S], cksum 0x3cbe (correct), seq 4184557870, win 12288, options [mss 1460,nop,wscale 6,sackOK,TS val 2478539442 ecr 0], length 0`
When I connect from localhost, there is no output in tcpdump.

Working locally for now, but am grateful for any help

**Comment by lemketron** [comment]
This is an old issue but in case it's still an issue or someone else finds this issue, please refer to the recommendations in this related [LGSVL simulator issue](https://github.com/lgsvl/simulator/issues/868#issuecomment-660844993).
